### ISSUE TITLE
Patient records: Types of input for Patient Vital Input Page

### ISSUE THREAD

**Issue by reynabxr** [NUS-Project-SaBai/FrontEnd#218]
**Issue**:
Inputs should allow float/decimal point numbers:
Patient Record > Vital Signs 
- Temperature (impt, at least one dp) 
- Height, Weight
- BP
- Blood Glucose (impt, at least one dp)

https://t.me/c/2042968232/768/777

Some devices may not be able to record decimal place, like BP.
The rest should have decimal place'

---
**Issue**: Able to enter anything in Left/Right eye vitals field

**Fix**: Possibly use regex to allow numerals and single slash. Or can have 2 input box for each with a pre-rendered slash.

**Todo**:
- Check with medicine what kind of input do they want their field to be? does it tally with what is currently present?

**Comment by nathantew14** [comment]
fixed with #262
