### ISSUE TITLE
Update Consultation "Referred For"

### ISSUE THREAD

**Issue by davidgohzk** [NUS-Project-SaBai/FrontEnd#272]
I think let's rename this to "Referral for" 
without the within the clinic

and then in the drip down, we include
1. Diagnostics
2. Acute
3. Chronic
4. Advanced Vision [Within clinic]
5. Glasses fitting [Within clinic]

**Comment by noahseethorcodes** [comment]
@davidgohzk resolved by #274 . Should I close the issue haha or do you wanna check
