### ISSUE TITLE
Colour Coordinate the Village Code

### ISSUE THREAD

**Issue by davidgohzk** [NUS-Project-SaBai/FrontEnd#90]
# Coordinating the village code

1. Update the utils/constants village code with an additional field called colour
2. Create a new component for the village code colour and ensure that all instances where the village code is used, it is colour coded

**Comment by RunjiaChen** [comment]
- create a new react component for colour coordination 
- ensure all instances of when the code shows up, it is colour coded

**Comment by keithxun** [comment]
Resolved with [pr#118](https://github.com/NUS-Project-SaBai/FrontEnd/pull/118)
